---
- name: Installer Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copier le fichier de configuration de Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Enable Nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: redémarer Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Installer PyMySQL avec pip
  pip:
    name: pymysql
    state: present
- name: Créer le répertoire /srv/app
  ansible.builtin.file:
    path: /srv/app
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
- name: Installer Git
  apt:
    name: git
    state: present
    update_cache: yes
  become: true

- name: Cloner le dépôt WordPress
  git:
    repo: https://github.com/WordPress/WordPress.git
    dest: /srv/app/wordpress

- name: Configurer wp-config.php
  template:
    src: wp-config.php.j2
    dest: /srv/app/wordpress/wp-config.php


